use_default_settings: true

server:
  secret_key: "${SEARXNG_SECRET}"
  limiter: false
  image_proxy: false

search:
  formats:
    - html
    - json
  default_lang: "en"
  autocomplete: "google"

outgoing:
  request_timeout: 15.0
  max_request_timeout: 20.0

engines:
  - name: google
    engine: google
    categories: [general, news]
    disabled: false
    weight: 1.5
    
  - name: bing
    engine: bing
    categories: [general, news]
    disabled: false
    weight: 1.3

  - name: google news
    engine: google_news
    categories: news
    disabled: false
    
  - name: bing news
    engine: bing_news
    categories: news
    disabled: false
    
  - name: reddit
    engine: google
    categories: [news, general]
    shortcut: re
    base_url: https://www.google.com/search
    custom_params:
      as_sitesearch: "reddit.com"
    weight: 1.5

  - name: yahoo news
    engine: yahoo
    categories: news
    shortcut: yhn
    disabled: false
    
  - name: qwant news
    engine: qwant
    categories: news
    shortcut: qwn
    disabled: false
    
  - name: twitter
    engine: google
    categories: [news, social media]
    base_url: https://www.google.com/search
    custom_params:
      as_sitesearch: "twitter.com"
    weight: 1.2
    
  - name: brave
    engine: brave
    categories: [general, news]
    shortcut: br
    disabled: false
    weight: 1.4